#
#     ,ad8888ba,                                                             88
#    d8"'    `"8b                                                            88
#   d8'                                                                      88
#   88             88       88  ,adPPYba,  ,adPPYYba,  8b,dPPYba,    ,adPPYb,88  8b,dPPYba,
#   88      88888  88       88  I8[    ""  ""     `Y8  88P'   `"8a  a8"    `Y88  88P'   "Y8
#   Y8,        88  88       88   `"Y8ba,   ,adPPPPP88  88       88  8b       88  88
#    Y8a.    .a88  "8a,   ,a88  aa    ]8I  88,    ,88  88       88  "8a,   ,d88  88
#     `"Y88888P"    `"YbbdP'Y8  `"YbbdP"'  `"8bbdP"Y8  88       88   `"8bbdP"Y8  88
#
#       Плагин был разработан Gusandr!
#   Все вопросы/предложения: ebli (discord) @sysclap (vk)


discord:
  # message лучше сильно не изменять, я немного намудрил с ним, ну уж извиняйте, в будущем обязательно сделаю как положено
  message: "**Игрок %s за котором вы сказали наблюдать написал %s в чат:**\n%s\n**Его координаты:** %s\n**Игроки в радиусе 70 блоков:** %s\n**Дата:** %s"
  url: "" # Ссылка на вебхук дискорда

players-under-surveillance:
  - "Fagi"
  - "musl1"
# - "" и так далее

date-format: "dd.MM.yyyy HH:mm:ss"