#
#     ,ad8888ba,                                                             88
#    d8"'    `"8b                                                            88
#   d8'                                                                      88
#   88             88       88  ,adPPYba,  ,adPPYYba,  8b,dPPYba,    ,adPPYb,88  8b,dPPYba,
#   88      88888  88       88  I8[    ""  ""     `Y8  88P'   `"8a  a8"    `Y88  88P'   "Y8
#   Y8,        88  88       88   `"Y8ba,   ,adPPPPP88  88       88  8b       88  88
#    Y8a.    .a88  "8a,   ,a88  aa    ]8I  88,    ,88  88       88  "8a,   ,d88  88
#     `"Y88888P"    `"YbbdP'Y8  `"YbbdP"'  `"8bbdP"Y8  88       88   `"8bbdP"Y8  88
#
#       The plugin was developed by Gusandr!
#   All questions/suggestions: ebli (discord)


discord:
  message: "**Player %s whom you said to watch wrote %s in the chat:**\n%s\n**His coordinates:** %s\n**Players within a 70 block radius:** %s\n**Date:**%s"
url: "" # Link to discord's webhook

players-under-surveillance:
  - "Phages"
  - "musl1"
# - "" and so on

date-format: "dd.MM.yyyy HH:mm:ss"
